package variable

import (
	"fmt"
)

func PlayVar(a int, b int) (int, int) {
	a, b = b, a
	fmt.Println(a, b)
	return a, b
}

func PlayBool(input bool)  {
	a := !input
	fmt.Println(a)
}

func PlayString() {


	fmt.Println("location is \"C:\\sdf\n.ext")

	fmt.Println(`// Generated by github.com/davyxu/cellnet/
protoc-gen-msg
// DO NOT EDIT!{{range .Protos}}
// Source: {{.Name}}{{end}}
package {{.PackageName}}
{{if gt .TotalMessages 0}}
import (
    "github.com/davyxu/cellnet"
    "reflect"
    _ "github.com/davyxu/cellnet/codec/pb"
)

{{end}}
func init() {
    {{range .Protos}}
    // {{.Name}}{{range .Messages}}
    cellnet.RegisterMessageMeta("pb","{{.FullName}}", reflect.TypeOf((*{{.Name}})(nil)).Elem(), {{.MsgID}})    {{end}}
    {{end}}
}`)
}